<?php
$this->jQuery();
$this->css($this->assetModule('css/admin.css'));
$this->js($this->assetModule('js/Chart.min.js'));
__('Toman');
?>
<div class="clearfix">
    <div class="page-header">
        <h1><?php _e('Summery report'); ?></h1>
    </div>
    <div class="clearfix row">
        <div class="col-md-6">
            <div class="alert alert-info" role="alert">
                <?php
                $price = sprintf(
                    '%s (%s)',
                    Pi::api('api', 'order')->viewPrice($list['total']['sum']),
                    Pi::api('api', 'order')->viewPrice($list['order']['sum'])
                );
                $count = sprintf(
                    '%s (%s)',
                    _number($list['total']['count']),
                    _number($list['order']['count'])
                );
                echo sprintf(
                    __('%s order and %s price.'),
                    $count,
                    $price
                ); ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="alert alert-success" role="alert">
                <?php echo sprintf(
                    __('%s paid invoice and %s price.'),
                    _number($list['paid']['count']),
                    Pi::api('api', 'order')->viewPrice($list['paid']['sum'])
                ); ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="alert alert-warning" role="alert">
                <?php echo sprintf(
                    __('%s unpaid invoice and %s price.'),
                    _number($list['unPaid']['count']),
                    Pi::api('api', 'order')->viewPrice($list['unPaid']['sum'])
                ); ?>
            </div>
        </div>
        <div class="col-md-6">
            <div class="alert alert-danger" role="alert">
                <?php echo sprintf(
                    __('%s delayed invoice and %s price.'),
                    _number($list['delayed']['count']),
                    Pi::api('api', 'order')->viewPrice($list['delayed']['sum'])
                ); ?>
            </div>
        </div>
    </div>
    <div class="clearfix row">
        <div class="col-md-6">
            <div class="page-header">
                <h4><?php _e('Chart sum'); ?></h4>
            </div>
            <div class="clearfix">
                <canvas id="chart-sum"></canvas>
            </div>
        </div>
        <div class="col-md-6">
            <div class="page-header">
                <h4><?php _e('Chart count'); ?></h4>
            </div>
            <div class="clearfix">
                <canvas id="chart-count"></canvas>
            </div>
        </div>
    </div>
    <hr />
    <div class="clearfix row">
        <div class="col-md-12">
            <div class="page-header">
                <h2><?php _e('Next days information'); ?></h2>
            </div>
            <div class="alert alert-info" role="alert">
                <?php echo sprintf(
                    __('we have %s invoice fpr next 10 days and total price %s'),
                    _number($list['next10']['count']),
                    Pi::api('api', 'order')->viewPrice($list['next10']['sum'])
                ); ?>
            </div>
            <div class="alert alert-info" role="alert">
                <?php echo sprintf(
                    __('we have %s invoice fpr next 30 days and total price %s'),
                    _number($list['next30']['count']),
                    Pi::api('api', 'order')->viewPrice($list['next30']['sum'])
                ); ?>
            </div>
        </div>
        <div class="col-md-4">
            <table class="table table-striped table-bordered table-sm">
                <tr>
                    <th><?php _e('Date'); ?></th>
                    <th><?php _e('Count'); ?></th>
                    <th><?php _e('Sum'); ?></th>
                </tr>
                <?php foreach ($list['next']['sum'] as $key => $value) { ?>
                    <tr>
                        <td><?php echo $this->escape($key); ?></td>
                        <td><?php echo $this->escape(_number($list['next']['count'][$key])); ?></td>
                        <td><?php echo $this->escape(Pi::api('api', 'order')->viewPrice($value)); ?></td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <div class="col-md-8">
            <!-- <div class="page-header">
                <h4><?php _e('Chart sum next months'); ?></h4>
            </div> -->
            <div class="clearfix">
                <canvas id="chart-sum-months"></canvas>
            </div>
            <!-- <div class="page-header">
                <h4><?php _e('Chart count next months'); ?></h4>
            </div>
            <!-- <div class="clearfix">
                <canvas id="chart-count-months"></canvas>
            </div> -->
        </div>
    </div>
</div>
<script>
    (function ($) {
        $(document).ready(function () {
            var ctx = document.getElementById('chart-sum').getContext('2d');
            new Chart(ctx, {
                type: 'pie',
                data: {
                    datasets: [{
                        data: [
                            <?php echo $list['paid']['sum']; ?>,
                            <?php echo $list['unPaid']['sum']; ?>,
                            <?php echo $list['delayed']['sum']; ?>,
                        ],
                        backgroundColor: [
                            'rgb(75, 192, 192)', // green
                            'rgb(255, 159, 64)', // orange
                            'rgb(255, 99, 132)', // red
                        ]
                    }],
                    labels: [
                        "<?php _e('Paid') ?>",
                        "<?php _e('UnPaid') ?>",
                        "<?php _e('Delayed') ?>",
                    ]
                },
                options: {
                    responsive: true
                }
            });
        });
        $(document).ready(function () {
            var ctx = document.getElementById('chart-count').getContext('2d');
            new Chart(ctx, {
                type: 'pie',
                data: {
                    datasets: [{
                        data: [
                            <?php echo $list['paid']['count']; ?>,
                            <?php echo $list['unPaid']['count']; ?>,
                            <?php echo $list['delayed']['count']; ?>,
                        ],
                        backgroundColor: [
                            'rgb(75, 192, 192)', // green
                            'rgb(255, 159, 64)', // orange
                            'rgb(255, 99, 132)', // red
                        ]
                    }],
                    labels: [
                        "<?php _e('Paid') ?>",
                        "<?php _e('UnPaid') ?>",
                        "<?php _e('Delayed') ?>",
                    ]
                },
                options: {
                    responsive: true
                }
            });
        });
        $(document).ready(function () {
            var ctx = document.getElementById('chart-sum-months').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: <?php echo json_encode(array_keys($list['next']['sum'])); ?>,
                    datasets: [{
                        label: "<?php _e('Sum of next months'); ?>",
                        fill: false,
                        backgroundColor: 'rgb(75, 192, 192)', // green
                        borderColor: 'rgb(75, 192, 192)',     // green
                        data: <?php echo json_encode(array_values($list['next']['sum'])); ?>,
                        //showLine: false,
                        pointRadius: 5,
                        pointHoverRadius: 10,
                    }]
                },
                options: {}
            });
        });
        $(document).ready(function () {
            var ctx = document.getElementById('chart-count-months').getContext('2d');
            var chart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: <?php echo json_encode(array_keys($list['next']['count'])); ?>,
                    datasets: [{
                        label: "<?php _e('Count of next months'); ?>",
                        fill: false,
                        backgroundColor: 'rgb(75, 192, 192)', // green
                        borderColor: 'rgb(75, 192, 192)',     // green
                        data: <?php echo json_encode(array_values($list['next']['count'])); ?>,
                        //showLine: false,
                        pointRadius: 5,
                        pointHoverRadius: 10,
                    }]
                },
                options: {}
            });
        });
    })(jQuery)
</script>